apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
  labels:
    app:  web-app
spec:
  replicas: 3 # number  of  pod copies
  selector:
    matchLabels:
      app:  web-app
  template:
    metadata:
      labels:
        app:  web-app
    spec:
      containers:
        - name: web-app
          image: kunalcoooode/nginx-app
          
          ports:
            - containerPort:  80